# Generated by Django 5.1.3 on 2024-11-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numero_celular', models.CharField(max_length=11)),
                ('numero_factura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('probabilidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ganador', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta.cliente')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta.premio')),
            ],
        ),
        migrations.CreateModel(
            name='Ruleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tiro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta.cliente')),
                ('premio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruleta.premio')),
            ],
        ),
    ]
