# Generated by Django 5.1.3 on 2024-11-25 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganador',
            name='fecha_ganador',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ruleta',
            name='fecha_tiro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
