# Generated by Django 5.1.3 on 2024-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0002_alter_ganador_fecha_ganador_alter_ruleta_fecha_tiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_factura',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
