# Generated by Django 5.1.1 on 2024-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0003_alter_cliente_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
