# Generated by Django 5.1.1 on 2024-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0005_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
